### ISSUE TITLE
Questions about the tutorial

### ISSUE THREAD

**Issue by henry2004y** [JuliaFolds/data-parallelism#26]
Hi,

This is a very nice tutorial! I have some questions and also comments after going through it:

1. I tried the example of letter count in the `mapreduce` section. On my Mac with Julia 1.5.1, the performance is a little bit surprising.

With 1 thread:
```julia
@btime f1 = mapreduce(x -> Dict(x => 1), mergewith!(+), str)
  8.830 μs (203 allocations: 27.66 KiB)
@btime f2 = ThreadsX.mapreduce(x -> SingletonDict(x => 1), mergewith!!(+), str)
  36.834 μs (308 allocations: 20.67 KiB)
```

With 4 threads:
```julia
@btime f1 = mapreduce(x -> Dict(x => 1), mergewith!(+), str)
  9.466 μs (203 allocations: 27.66 KiB)
@btime f2 = ThreadsX.mapreduce(x -> SingletonDict(x => 1), mergewith!!(+), str)
  55.702 μs (1347 allocations: 86.23 KiB)
```

Shouldn't the threaded version be faster? Is the workload here too small to show the speedup? I guess there is threading launching overhead, but are these numbers normal?

2. In the `Practical example: Stopping time of Collatz function` section,
```julia
julia> Threads.nthreads()  # I started `julia` with `-t 4`
4

julia> using BenchmarkTools

julia> @btime map(collatz_stopping_time, 1:100_000);
  18.116 ms (2 allocations: 781.33 KiB)

julia> @btime ThreadsX.map(collatz_stopping_time, 1:100_000);
  5.391 ms (1665 allocations: 7.09 MiB)
```

With 4 threads, why is the total memory usage ~10 times larger? Is it useful in general to check the memory usage for parallel programs?

3. The section `Practical example: Histogram of stopping time of Collatz function`  shows a more complicated usage of the `FLoops` package, which is a little bit harder to follow without knowing the package ahead.

**Comment by tkf** [comment]
> Shouldn't the threaded version be faster?

Thanks for bringing this up! I should mention in the tutorial that almost all the examples (except the "practical" examples) use too small input size for observing the speedup.  I chose small examples so that you can see the input and output by eyes.  So, for the histogram example, you'd need much longer string to get the benefit of it:


```julia
julia> Threads.nthreads()
4

julia> str = join(rand('a':'k', 10_000_000));

julia> @btime ThreadsX.mapreduce(x -> SingletonDict(x => 1), mergewith!!(+), str);
  27.503 ms (1443 allocations: 121.67 KiB)

julia> @btime mapreduce(x -> SingletonDict(x => 1), mergewith!!(+), str);
  120.366 ms (7 allocations: 1.63 KiB)

julia> @btime mapreduce(x -> Dict(x => 1), mergewith!(+), str);
  1.716 s (40000003 allocations: 5.07 GiB)
```

I should mention that they are toy examples and you should bump up the problem size to see the benefit of multi-threading (or actually use larger data size in the tutorial).

> With 4 threads, why is the total memory usage ~10 times larger?

Hmm... This one is interesting. A short answer is I don't know.

ThreadsX.jl uses [`nthreads() * 8` tasks by default](https://github.com/tkf/ThreadsX.jl/blob/7a98c2407a45a02d818c85729570e47c3dbccd8f/src/basesizes.jl#L1) and the array used for each task are thrown away when they are merged. So it at least requires (1 + 31/32) ≈ 1.96 times more memory. Also, since ThreadsX.jl's `map` is based on `push!` which grows the vector by the factor of two, it can double the usage at most.  But that's far off from 10x allocations you see.

> The section `Practical example: Histogram of stopping time of Collatz function`  shows a more complicated usage of the `FLoops` package, which is a little bit harder to follow without knowing the package ahead.

Yeah, that example is the most complicated one and I wanted to use it for "showing off" some complex code you can write. I'm still struggling to find the best way to explain how `@floop` + `@reduce` work. I should probably add a diagram or something.

**Comment by henry2004y** [comment]
Thanks, these are indeed very helpful! I am surprised and also glad to see the usage of `SingletonDict` can tremendously reduce the memory allocation. Looking forward to these features being absorbed into the Julia base in the near future!
